# Generated by Django 3.2.2 on 2021-05-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='career',
            new_name='profession',
        ),
    ]
