# Generated by Django 3.2.2 on 2021-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_career_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.CharField(max_length=100, verbose_name='経験した業務')),
                ('cyears', models.FloatField(default=0, verbose_name='経験年数')),
                ('comment', models.TextField(verbose_name='経験した業務内容')),
            ],
            options={
                'verbose_name_plural': '経験業種',
            },
        ),
    ]
